#!/bin/sh

# add color to commands
alias \
  ls="exa --color=always" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  dir='dir --color=auto' \
  vdir='vdir --color=auto' \
  grep='grep --color=auto' \
  fgrep='fgrep --color=auto' \
  egrep='egrep --color=auto'

# shortcuts
alias \
  startx='startx $HOME/.config/X11/xinitrc' \
  sysinfo="inxi -Fxz" \
  untar="tar -xvf" \
  vim="nvim" \
  v="nvim" \
  rm="rm -vI" \
  cp="cp -iv" \
  ..="cd .." \
  mv="mv -iv" \
  mv="mv -iv" \
  media="cd /media/rafa/Media" \
  dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

# search for all scripts and dotfiles, then open them with editor of choice
sc() {
  find ~/.zshenv ~/.config/{bspwm,dunst,fontconfig,git,greenclip.cfg,gtk-3.0,htop,kitty,lazygit,lf,mimeapps.list,mozifire,mpd,mpv,ncmpcpp,neofetch,newsboat,npm,nvim,picom,polybar,rofi,sxhkd,user-dirs.dirs,X11,zsh} \
    ~/.local/bin/{scripts,cron,statusbar} ~/.local/share/rais -type f |
    fzf --preview 'bat --color=always --line-range :50 {}' | xargs -r "$EDITOR"
}

# fd - cd into any hidden directory of the current folder
fcd() {
  dir=$(find "${1:-.}" -type d 2>/dev/null | fzf +m) && cd "$dir" || exit
}

# fkill - kill process
fkill() {
  pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')

  if [ "x$pid" != "x" ]; then
    echo "$pid" | xargs kill -"${1:-9}"
  fi
}

# cdf - cd into the directory of the selected file
cdf() {
  file=$(find "${1:-.}" -type f | fzf +m -q "$1") && dir=$(dirname "$file") && cd "$dir" || exit
}

# search for a package and installed if needed
search() {
  pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S --needed
}
