#!/bin/sh

# add color to commands
alias \
  ls="exa --color=always" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  dir='dir --color=auto' \
  vdir='vdir --color=auto' \
  grep='grep --color=auto' \
  fgrep='fgrep --color=auto' \
  egrep='egrep --color=auto'

# shortcuts
alias \
  sx="$HOME/.config/X11/xinitrc" \
  sysinfo="inxi -Fxz" \
  untar="tar -xvf" \
  icat="kitty +kitten icat" \
  vim="nvim" \
  v="nvim" \
  rm="rm -vI" \
  cp="cp -iv" \
  ..="cd .." \
  mv="mv -iv" \
  mv="mv -iv" \
  media="cd /media/rafa/Media" \
  dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

# git
alias \
  ga="git add" \
  gaa="git add --all" \
  gb="git branch -a" \
  gcm="git commit -m" \
  gd="git diff" \
  gp="git push" \
  gl="git pull" \
  gll="git log" \
  gs="git status" \
  gr="git remote -v" \
  grm="git rm" \
  grmc="git rm --cached" \
  gmv="git mv"

alias \
  dota="dot add" \
  dotaa="dot add --all" \
  dotb="dot branch -a" \
  dotcm="dot commit -m" \
  dotd="dot diff" \
  dotp="dot push" \
  dotl="dot pull" \
  dotll="dot log" \
  dots="dot status" \
  dotr="dot remote -v" \
  dotrm="dot rm" \
  dotrmc="dot rm --cached" \
  dotmv="dot mv"

# search for all scripts and dotfiles, then open them with editor of choice
files=(~/.zshenv ~/.config/{bspwm,dunst,fontconfig,git,greenclip.cfg,gtk-3.0,htop,kitty,lazygit,lf,mimeapps.list,mozifire,mpd,mpv,ncmpcpp,neofetch,newsboat,npm,nvim,picom,polybar,rofi,sxhkd,user-dirs.dirs,X11,zsh}
  ~/.local/bin/{scripts,cron,statusbar} ~/.local/share/rais)
dotf() {
  find $files -type f |
    fzf --preview 'bat --color=always --line-range :50 {}' | xargs -r "$EDITOR"
}

# fd - cd into any hidden directory of the current folder
fcd() {
  dir=$(find "${1:-.}" -type d 2>/dev/null | fzf +m) && cd "$dir" || exit
}

# fkill - kill process
fkill() {
  pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')

  if [ "x$pid" != "x" ]; then
    echo "$pid" | xargs kill -"${1:-9}"
  fi
}

# cdf - cd into the directory of the selected file
cdf() {
  file=$(find "${1:-.}" -type f | fzf +m -q "$1") && dir=$(dirname "$file") && cd "$dir" || exit
}

# search for a package and installed if needed
pacfind() {
  paru -Sl | awk '{print $2($4=="" ? "" : " *")}' | fzf --multi --preview 'paru -Si {1}' | xargs -ro paru -S --needed
}
