#!/bin/sh

# add color to commands
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias dir='dir --color=auto'
alias ls='ls -Fh --color=always'
alias ll='ls -Flh --color=always'
alias lla='ls -FlAh --color=always'
alias d='dirs -v'

for index in {1..9}; do
	alias "$index"="cd +${index}"
done

# shortcuts
if command -v xdg-open >/dev/null 2>&1; then
	alias open='xdg-open'
fi
alias sys='systemctl'
alias icat='kitty +kitten icat'
alias cp='cp -iv'
alias mv='mv -iv'
alias nuke='rm -rI'
alias rm='rm -vI'
alias sudo='sudo '
alias untar='tar -xvf'
alias v='nvim'
alias vim='nvim'
alias cm='chezmoi'
alias lg='lazygit'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# git
alias g='git'
alias ga='git add'
alias gcl='git clone'
alias cdg='cd $(git rev-parse --show-toplevel)'
alias gaa='git add --all'
alias gb='git branch -a'
alias gc='git commit'
alias gcm='git commit -m'
alias gd='git diff'
alias gp='git push'
alias gl='git pull'
alias gll='git log'
alias gs='git status'
alias gr='git remote -v'
alias grm='git rm'
alias grmc='git rm --cached'
alias gmv='git mv'
