#!/bin/sh

# add color to commands
alias \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    dir='dir --color=auto' \
    vdir='vdir --color=auto' \
    grep='grep --color=auto' \
    fgrep='fgrep --color=auto' \
    egrep='egrep --color=auto'

if exa >/dev/null 2>&1; then
    alias \
        ls='exa --color=always' \
        ll='exa -l --color=always' \
        lla='exa -la --color=always'
else
    alias \
        ls='ls -F --color=always' \
        ll='ls -Fl --color=always' \
        lla='ls -Fla --color=always'
fi

# shortcuts
alias \
    sx='startx $HOME/.config/X11/xinitrc' \
    nuke='rm -rf' \
    sctl='sudo systemctl' \
    open='xdg-open' \
    sysinfo="inxi -Fxz" \
    untar='tar -xvf' \
    icat='kitty +kitten icat' \
    vim='nvim' \
    v='nvim' \
    rm='rm -vI' \
    cp='cp -iv' \
    mv='mv -iv' \
    d='kitty +kitten diff' \
    dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' \
    weather='curl https://wttr.in/Buenos_Aires' \
    ..='cd ..' \
    ...='cd ../..' \
    ....='cd ../../..'

# git
alias \
    ga='git add' \
    gcl='git clone' \
    gcd='cd $(git rev-parse --show-toplevel)' \
    gaa='git add --all' \
    gb='git branch -a' \
    gcm='git commit -m' \
    gd='git diff' \
    gp='git push' \
    gl='git pull' \
    gll='git log' \
    gs='git status' \
    gr='git remote -v' \
    grm='git rm' \
    grmc='git rm --cached' \
    gmv='git mv'

alias \
    dota='dot add' \
    dotaa='dot add --all' \
    dotb='dot branch -a' \
    dotcm='dot commit -m' \
    dotd='dot diff' \
    dotp='dot push' \
    dotl='dot pull' \
    dotll='dot log' \
    dots='dot status' \
    dotr='dot remote -v' \
    dotrm='dot rm' \
    dotrmc='dot rm --cached' \
    dotmv='dot mv'

# devour
if devour >/dev/null 2>&1; then
    alias \
        mpv='devour mpv' \
        zathura='devour zathura' \
        sxiv='devour sxiv' \
        firefox='devour firefox'
fi
