import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[font]
size = 12

[font.normal]
family = "Cascadia Mono"
# family = "JetBrains Mono"
# family = "Fira Code"
# family = "Hack"
# family = "Source Code Pro"
# family = "Maple Mono"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"
# style = "Bold Italic"
# family = "VictorMono Nerd Font"

[font.bold_italic]
style = "Bold Italic"

[mouse]
hide_when_typing = true

# https://github.com/alacritty/alacritty/issues/6156#issuecomment-1924172603
[env]
TERM = "xterm-256color"

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
regex = "[a-f0-9]{40}|[a-f0-9]{7,8}"
binding = { key = "H", mods = "Control|Shift" }
action = "Copy"

[[hints.enabled]]
regex = ''''(/?[^/ \t\"']*[a-zA-Z0-9][^/ \t\"':]*/([^/ \t\"']+/?)*)\
    |(/[^/ \t\"']*[a-zA-Z0-9][^/ \t\"']*)'''
action = "Copy"
hyperlinks = true
binding = { key = "E", mods = "Control|Shift" }
