#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

xrdb ~/.config/X11/Xresources
setxkbmap -layout es -variant winkeys &
xsetroot -cursor_name left_ptr
xset r rate 200 40 &

session=${1:-bspwm}

case $session in
bspwm) exec bspwm ;;
kde) exec startplasma-x11 ;;
# No known session, try to run it as command
*) exec $1 ;;
esac
