#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
[[ -f ~/.config/X11/Xresources ]] && xrdb -merge .config/X11/Xresources

setxkbmap -layout es -variant winkeys &
xsetroot -cursor_name left_ptr
exec bspwm
