theme = "vim_dark_high_contrast"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[keys.insert]
"C-c" = "normal_mode"

[editor.file-picker]
hidden = false
