title-bar=no
osc=no
osd-bar=no

# circumvent subtitle or OSD bad positioning when watch later options are used
sub-visibility=no
watch-later-options-remove=sub-pos
watch-later-options-remove=osd-margin-y

screenshot-directory=~/Pictures/mpv
screenshot-template="%F-%n"

save-position-on-quit=yes
save-watch-history=yes
write-filename-in-watch-later-config=yes
autofit=50%x50%

vo=gpu-next
gpu-api=vulkan
hwdec=vaapi
gpu-context=waylandvk
hdr-compute-peak=yes
video-sync=display-resample
tone-mapping=bt.2390
target-colorspace-hint=no
interpolation=yes
tscale=oversample
