#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
picom -b --experimental-backends &
killall mpd
mpd &
"$HOME"/.config/polybar/launch.sh
xwallpaper --zoom ~/.local/share/wall/wallhaven-1kjplv.jpg
xmodmap ~/.config/X11/xmodmap
killall "flameshot"
flameshot & # screenshot utility
killall "dunst"
dunst & # notification daemon
killall "unclutter"
unclutter & # clean cursor when in idle
killall "greenclip"
greenclip daemon &

bspc monitor -d 1 2 3 4 5

# Rules
bspc rule -a firefox desktop='^2' focus=on follow=on

# Truncate a couple of common commands that are used herein.
_bc() {
    bspc config "$@"
}

### BSPWM configuration ###
_bc top_padding 36
_bc border_width 4
_bc window_gap 13
_bc split_ratio 0.52
_bc borderless_monocle true
_bc gapless_monocle true

# Colors
_bc normal_border_color "#c8ccd4"
_bc focused_border_color "#61afef"
