RIGHT seek 5 exact
LEFT seek -5 exact
+ add sub-scale +0.1
- add sub-scale -0.1

# crop.lua
# ==========
# start cropping
c script-message-to crop start-crop hard
alt+c script-message-to crop start-crop soft
# delogo mode can be used like so
l script-message-to crop start-crop delogo
# remove the crop
d vf clear crop # https://github.com/occivink/mpv-scripts/issues/76

# or use the ready-made "toggle" binding
C script-message-to crop toggle-crop hard

# encode.lua
# ============
# use default profile (makes vp8 webms)
# e script-message-to encode set-timestamp

# use custom webm profile, the argument name must correspond to an existing .conf file (see script-opts/)
# alt+e script-message-to encode set-timestamp encode_webm

# use custom profile
e script-message-to encode set-timestamp encode_slice

# seek-to.lua
# =============
t script-message-to seek_to toggle-seeker
